[package]
name = "msi-gpu-mode"
version = "0.1.0"
edition = "2024"
description = "Switch the GPU mode of MSI laptops on Linux"

[dependencies]
clap = { version = "4", features = ["derive"] }
iced = { version = "0.14", default-features = false, features = ["tiny-skia", "thread-pool", "linux-theme-detection", "wayland", "x11"] }
libc = "0.2"

[profile.release]
lto = true
strip = true
